name: Auto Green

on:
  schedule:
    - cron: '0 6 * * *' # Setiap hari jam 6 pagi UTC (13:00 WIB)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install jsonfile moment moment-timezone simple-git

      - name: Enable ESM module type
        run: |
          echo "{ \"type\": \"module\" }" > package.json

      - name: Set Git Identity
        run: |
          git config --global user.name "Machfudin"
          git config --global user.email "machfudn@users.noreply.github.com"

      - name: Run commit script
        run: node index.js

      - name: Push commits
        run: |
          git add .
          git commit -m "Auto commit from GitHub Actions" || echo "Nothing to commit"
          git push
